# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpd', '0012_splitting_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='knowledge_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lpd.KnowledgeComponent'),
        ),
    ]
