# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpd', '0013_kc_add_related_name_for_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lpd.Section'),
        ),
    ]
