# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lpd.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lpd', '0014_section_add_related_name_for_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPDExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to=lpd.storage.export_path)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requested_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='lpd.LearnerProfileDashboard')),
            ],
        ),
    ]
