# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpd', '0015_add_pdf_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecomponent',
            name='lpd',
            field=models.ForeignKey(blank=True, help_text=b"LPD that this knowledge component is associated with. Note: If a knowledge component is associated with an answer option, it is implicitly linked to an LPD via that answer option: Every answer option is associated with a (quantitative) question, and every question is associated with a section, which is in turn associated with an LPD. So in this case, setting this field is not strictly required. However, if a knowledge component represents a group (and is not associated with an answer option), this field should be set to the LPD for which the knowledge component was (or is intended to be) used: Without an explicit association between knowledge components and LPDs, it wouldn't be possible to filter group scores by LPD/course run. This is because there is no link between a specific group score and the set of learner answers that it was derived from, so it is not possible to trace the group score back to a specific set of qualitative questions (which would be a prerequisite for tracing the score all the way back to a specific LPD).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_components', to='lpd.LearnerProfileDashboard'),
        ),
    ]
